### ISSUE TITLE
Execution from packaged jar fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MichaelTamm/junit-toolbox#2]
```
Within our environment it is necessary to execute the tests from the packaged 
jar file. This fails because WildcardPatternSuite.getBaseDir() returns a File. 
For us it would be better if it would return an InputStream instead.

What steps will reproduce the problem?
You can reproduce the problem by following the steps described on:
http://stackoverflow.com/questions/18055189/why-my-uri-is-not-hierarchical

What is the expected output? What do you see instead?
Expected is a runing test suite.
Instead I get an exception:
Testcase: initializationError(<myPackage>.MyUnitTests): 
Caused an ERROR URI is not hierarchical
java.lang.IllegalArgumentException: URI is not hierarchical
   at java.io.File.<init>(File.java:363)
   at com.googlecode.junittoolbox.WildcardPatternSuite.getBaseDir(WildcardPatternSuite.java:135)
   at com.googlecode.junittoolbox.WildcardPatternSuite.findSuiteClasses(WildcardPatternSuite.java:59)
   at com.googlecode.junittoolbox.WildcardPatternSuite.getSuiteClasses(WildcardPatternSuite.java:54)
   at com.googlecode.junittoolbox.WildcardPatternSuite.<init>(WildcardPatternSuite.java:180)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
   at java.lang.reflect.Constructor.newInstance(Constructor.java:513)


What version of the product are you using? On what operating system?
Version 1.5
Windows 7 environment

Please provide any additional information below.


```

Original issue reported on code.google.com by `goo...@canoo.com` on 23 Jan 2014 at 1:41

**Comment by MichaelCowanPdx** [comment]
Any updates on this? It is still happening.

**Comment by hsyed** [comment]
Can't run the tests from bazel as the tests are always run from a packaged jar.

**Comment by JohannesRudolph** [comment]
Same issue here
