### ISSUE TITLE
Junit toolbox API + ParallelSuite throws java.util.NoSuchElementException at java.base/java.util.LinkedList.removeFirst

### ISSUE THREAD

**Issue by sac10nikam** [MichaelTamm/junit-toolbox#28]
OS - MacOs
Vertx framework + junit google toolbox library.
Description: I am trying to execute junit's ParallelSuite

2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger] MyTestSuite > package.MyTest.classMethod FAILED
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]     java.util.NoSuchElementException
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at java.base/java.util.LinkedList.removeFirst(LinkedList.java:274)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at java.base/java.util.LinkedList.pop(LinkedList.java:805)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at io.vertx.ext.unit.junit.VertxUnitRunner.popContext(VertxUnitRunner.java:234)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at io.vertx.ext.unit.junit.RunTestOnContext$1.evaluate(RunTestOnContext.java:123)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.Suite.runChild(Suite.java:128)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.Suite.runChild(Suite.java:27)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1409)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
2022-12-05T11:24:48.753+0530 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
2022-12-05T11:24:48.754+0530 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
2

**Comment by sac10nikam** [comment]
@MichaelTamm can you help here?
