### ISSUE TITLE
Suit should not create classes that do not have @Test annotation inside

### ISSUE THREAD

**Issue by lalili** [MichaelTamm/junit-toolbox#8]
If you run a suitecase that include all the classes from package:
@RunWith(WildcardPatternSuite.class)
@SuiteClasses("**/*.class")

An exception is thrown for classes that are not tests:

java.lang.Exception: Test class should have exactly one public zero-argument constructor
	at org.junit.runners.BlockJUnit4ClassRunner.validateZeroArgConstructor(BlockJUnit4ClassRunner.java:147)
	at org.junit.runners.BlockJUnit4ClassRunner.validateConstructor(BlockJUnit4ClassRunner.java:124)
	at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:355)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:57)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
	at org.junit.runners.Suite.<init>(Suite.java:101)

**Comment by MichaelTamm** [comment]
The value of the `@SuiteClasses` annotation should only include test classes.
For example: `@SuiteClasses("**/*Test.class")`

**Comment by lalili** [comment]
Hi Michael, 
I understand that you expect to get a name pattern. But my tests cannot be found by a name / package pattern. They share their package with test util files

**Comment by MichaelTamm** [comment]
Hmm, it is considered good practice to name all your test classes with the suffix "Test" and all other classes differently. This is what the junit task of Ant and the surefire plugin of Maven and probably most Java programmers expect.

Nevertheless, I guess I can improve the WildcardPatternSuite. I will reopen the issue ...

**Comment by lalili** [comment]
thank you Michael, I'll give it a try. (Its a legacy code, so I couldn't easily refactor it to build a matching name pattern)
